### Login
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "{{ username }}",
  "password": "{{ password }}"
}

### GET User
GET http://localhost:8080/user
Authorization: Bearer {{ jwt }}

### GET All Products
GET http://localhost:8080/products
Authorization: Bearer {{ jwt }}

### GET Product By Id
GET http://localhost:8080/products/62330f3d824b51421e4c3905
Authorization: Bearer {{ jwt }}

### Add Product
POST http://localhost:8080/products
Authorization: Bearer {{ jwt }}
Content-Type: application/json

{
  "name": "Product 1",
  "description": "Sample description"
}

### Delete Product
DELETE http://localhost:8080/products/62330f3d824b51421e4c3905
Authorization: Bearer {{ jwt }}
